name: ApiLess MelonLoader Toolchain
description: MelonLoader's toolchain, but as a GitHub Action. Useful for CI builds of MelonLoader mods.
author: Estyms, tetra-fox

inputs:
  game:
    description: gameSlug from MelonLoader API
    required: true
  game_path:
    description: Path to your Unity game
    required: true
  game_executable:
    description: Your Unity game's executable name
    required: true
  unity_version:
    description: Override Unity version (If it was not automatically found)
    required: false
  il2cpp_version:
    description: Il2Cpp Version of the game
    required: false
  mapping_url:
    description: Url of the game assembly mapping
    required: false
  unhollower_version:
    description: Unhollower version
    required: false
  obfuscation_regex:
    description: File obfuscation regex
    required: false
  work_path:
    description: Where tools will be downloaded
    default: ${{ github.workspace }}/ml-gen
    required: false
  output_path:
    description: Output directory for libraries
    required: false
  ml_version:
    description: MelonLoader release tag name
    default: latest
    required: false
  github_token:
    description: GitHub token to download tools
    default: ${{ github.token }}
    required: false
    
runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "zap"
  color: "purple"
